services:
  mysql_db:
    image: mysql/mysql-server:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: usr
      MYSQL_PASSWORD: user123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-db
      PMA_USER: usr
      PMA_PASSWORD: user123
    networks:
      - app-network
    depends_on:
      - mysql_db

  nginx:
    image: nginx:1.29.0-alpine
    container_name: nginx-ui
    restart: unless-stopped
    ports:
      - "10002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - phpmyadmin

volumes:
    mysql-data:
        driver: local

networks:
  app-network:
    driver: bridge
